#!/bin/bash
# file: renameURLflagsAPI.sh
sed -i 's|https://restcountries.eu/data/afg.svg",|https://flagcdn.com/w20/af.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/alb.svg",|https://flagcdn.com/w20/al.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/dza.svg",|https://flagcdn.com/w20/dz.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/asm.svg",|https://flagcdn.com/w20/as.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/and.svg",|https://flagcdn.com/w20/ad.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/ago.svg",|https://flagcdn.com/w20/ao.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/aia.svg",|https://flagcdn.com/w20/ai.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/ata.svg",|https://flagcdn.com/w20/aq.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/atg.svg",|https://flagcdn.com/w20/ag.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/arg.svg",|https://flagcdn.com/w20/ar.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/arm.svg",|https://flagcdn.com/w20/am.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/abw.svg",|https://flagcdn.com/w20/aw.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/aus.svg",|https://flagcdn.com/w20/au.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/aut.svg",|https://flagcdn.com/w20/at.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/aze.svg",|https://flagcdn.com/w20/az.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/bhs.svg",|https://flagcdn.com/w20/bs.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/bhr.svg",|https://flagcdn.com/w20/bh.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/bgd.svg",|https://flagcdn.com/w20/bd.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/brb.svg",|https://flagcdn.com/w20/bb.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/blr.svg",|https://flagcdn.com/w20/by.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/bel.svg",|https://flagcdn.com/w20/be.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/blz.svg",|https://flagcdn.com/w20/bz.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/ben.svg",|https://flagcdn.com/w20/bj.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/bmu.svg",|https://flagcdn.com/w20/bm.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/btn.svg",|https://flagcdn.com/w20/bt.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/bol.svg",|https://flagcdn.com/w20/bo.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/bes.svg",|https://flagcdn.com/w20/bq.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/bih.svg",|https://flagcdn.com/w20/ba.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/bwa.svg",|https://flagcdn.com/w20/bw.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/bvt.svg",|https://flagcdn.com/w20/bv.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/bra.svg",|https://flagcdn.com/w20/br.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/iot.svg",|https://flagcdn.com/w20/io.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/brn.svg",|https://flagcdn.com/w20/bn.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/bgr.svg",|https://flagcdn.com/w20/bg.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/bfa.svg",|https://flagcdn.com/w20/bf.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/bdi.svg",|https://flagcdn.com/w20/bi.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/cpv.svg",|https://flagcdn.com/w20/cv.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/khm.svg",|https://flagcdn.com/w20/kh.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/cmr.svg",|https://flagcdn.com/w20/cm.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/can.svg",|https://flagcdn.com/w20/ca.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/cym.svg",|https://flagcdn.com/w20/ky.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/caf.svg",|https://flagcdn.com/w20/cf.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/tcd.svg",|https://flagcdn.com/w20/td.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/chl.svg",|https://flagcdn.com/w20/cl.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/chn.svg",|https://flagcdn.com/w20/cn.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/cxr.svg",|https://flagcdn.com/w20/cx.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/cck.svg",|https://flagcdn.com/w20/cc.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/col.svg",|https://flagcdn.com/w20/co.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/com.svg",|https://flagcdn.com/w20/km.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/cod.svg",|https://flagcdn.com/w20/cd.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/cog.svg",|https://flagcdn.com/w20/cg.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/cok.svg",|https://flagcdn.com/w20/ck.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/cri.svg",|https://flagcdn.com/w20/cr.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/hrv.svg",|https://flagcdn.com/w20/hr.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/cub.svg",|https://flagcdn.com/w20/cu.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/cuw.svg",|https://flagcdn.com/w20/cw.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/cyp.svg",|https://flagcdn.com/w20/cy.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/cze.svg",|https://flagcdn.com/w20/cz.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/civ.svg",|https://flagcdn.com/w20/ci.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/dnk.svg",|https://flagcdn.com/w20/dk.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/dji.svg",|https://flagcdn.com/w20/dj.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/dma.svg",|https://flagcdn.com/w20/dm.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/dom.svg",|https://flagcdn.com/w20/do.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/ecu.svg",|https://flagcdn.com/w20/ec.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/egy.svg",|https://flagcdn.com/w20/eg.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/slv.svg",|https://flagcdn.com/w20/sv.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/gnq.svg",|https://flagcdn.com/w20/gq.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/eri.svg",|https://flagcdn.com/w20/er.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/est.svg",|https://flagcdn.com/w20/ee.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/swz.svg",|https://flagcdn.com/w20/sz.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/eth.svg",|https://flagcdn.com/w20/et.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/flk.svg",|https://flagcdn.com/w20/fk.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/fro.svg",|https://flagcdn.com/w20/fo.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/fji.svg",|https://flagcdn.com/w20/fj.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/fin.svg",|https://flagcdn.com/w20/fi.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/fra.svg",|https://flagcdn.com/w20/fr.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/guf.svg",|https://flagcdn.com/w20/gf.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/pyf.svg",|https://flagcdn.com/w20/pf.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/atf.svg",|https://flagcdn.com/w20/tf.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/gab.svg",|https://flagcdn.com/w20/ga.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/gmb.svg",|https://flagcdn.com/w20/gm.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/geo.svg",|https://flagcdn.com/w20/ge.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/deu.svg",|https://flagcdn.com/w20/de.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/gha.svg",|https://flagcdn.com/w20/gh.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/gib.svg",|https://flagcdn.com/w20/gi.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/grc.svg",|https://flagcdn.com/w20/gr.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/grl.svg",|https://flagcdn.com/w20/gl.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/grd.svg",|https://flagcdn.com/w20/gd.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/glp.svg",|https://flagcdn.com/w20/gp.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/gum.svg",|https://flagcdn.com/w20/gu.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/gtm.svg",|https://flagcdn.com/w20/gt.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/ggy.svg",|https://flagcdn.com/w20/gg.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/gin.svg",|https://flagcdn.com/w20/gn.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/gnb.svg",|https://flagcdn.com/w20/gw.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/guy.svg",|https://flagcdn.com/w20/gy.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/hti.svg",|https://flagcdn.com/w20/ht.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/hmd.svg",|https://flagcdn.com/w20/hm.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/vat.svg",|https://flagcdn.com/w20/va.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/hnd.svg",|https://flagcdn.com/w20/hn.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/hkg.svg",|https://flagcdn.com/w20/hk.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/hun.svg",|https://flagcdn.com/w20/hu.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/isl.svg",|https://flagcdn.com/w20/is.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/ind.svg",|https://flagcdn.com/w20/in.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/idn.svg",|https://flagcdn.com/w20/id.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/irn.svg",|https://flagcdn.com/w20/ir.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/irq.svg",|https://flagcdn.com/w20/iq.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/irl.svg",|https://flagcdn.com/w20/ie.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/imn.svg",|https://flagcdn.com/w20/im.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/isr.svg",|https://flagcdn.com/w20/il.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/ita.svg",|https://flagcdn.com/w20/it.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/jam.svg",|https://flagcdn.com/w20/jm.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/jpn.svg",|https://flagcdn.com/w20/jp.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/jey.svg",|https://flagcdn.com/w20/je.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/jor.svg",|https://flagcdn.com/w20/jo.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/kaz.svg",|https://flagcdn.com/w20/kz.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/ken.svg",|https://flagcdn.com/w20/ke.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/kir.svg",|https://flagcdn.com/w20/ki.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/prk.svg",|https://flagcdn.com/w20/kp.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/kor.svg",|https://flagcdn.com/w20/kr.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/kwt.svg",|https://flagcdn.com/w20/kw.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/kgz.svg",|https://flagcdn.com/w20/kg.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/lao.svg",|https://flagcdn.com/w20/la.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/lva.svg",|https://flagcdn.com/w20/lv.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/lbn.svg",|https://flagcdn.com/w20/lb.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/lso.svg",|https://flagcdn.com/w20/ls.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/lbr.svg",|https://flagcdn.com/w20/lr.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/lby.svg",|https://flagcdn.com/w20/ly.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/lie.svg",|https://flagcdn.com/w20/li.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/ltu.svg",|https://flagcdn.com/w20/lt.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/lux.svg",|https://flagcdn.com/w20/lu.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mac.svg",|https://flagcdn.com/w20/mo.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mdg.svg",|https://flagcdn.com/w20/mg.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mwi.svg",|https://flagcdn.com/w20/mw.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mys.svg",|https://flagcdn.com/w20/my.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mdv.svg",|https://flagcdn.com/w20/mv.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mli.svg",|https://flagcdn.com/w20/ml.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mlt.svg",|https://flagcdn.com/w20/mt.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mhl.svg",|https://flagcdn.com/w20/mh.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mtq.svg",|https://flagcdn.com/w20/mq.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mrt.svg",|https://flagcdn.com/w20/mr.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mus.svg",|https://flagcdn.com/w20/mu.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/myt.svg",|https://flagcdn.com/w20/yt.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mex.svg",|https://flagcdn.com/w20/mx.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/fsm.svg",|https://flagcdn.com/w20/fm.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mda.svg",|https://flagcdn.com/w20/md.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mco.svg",|https://flagcdn.com/w20/mc.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mng.svg",|https://flagcdn.com/w20/mn.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mne.svg",|https://flagcdn.com/w20/me.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/msr.svg",|https://flagcdn.com/w20/ms.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mar.svg",|https://flagcdn.com/w20/ma.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/moz.svg",|https://flagcdn.com/w20/mz.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mmr.svg",|https://flagcdn.com/w20/mm.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/nam.svg",|https://flagcdn.com/w20/na.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/nru.svg",|https://flagcdn.com/w20/nr.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/npl.svg",|https://flagcdn.com/w20/np.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/nld.svg",|https://flagcdn.com/w20/nl.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/ncl.svg",|https://flagcdn.com/w20/nc.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/nzl.svg",|https://flagcdn.com/w20/nz.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/nic.svg",|https://flagcdn.com/w20/ni.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/ner.svg",|https://flagcdn.com/w20/ne.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/nga.svg",|https://flagcdn.com/w20/ng.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/niu.svg",|https://flagcdn.com/w20/nu.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/nfk.svg",|https://flagcdn.com/w20/nf.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mnp.svg",|https://flagcdn.com/w20/mp.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/nor.svg",|https://flagcdn.com/w20/no.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/omn.svg",|https://flagcdn.com/w20/om.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/pak.svg",|https://flagcdn.com/w20/pk.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/plw.svg",|https://flagcdn.com/w20/pw.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/pse.svg",|https://flagcdn.com/w20/ps.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/pan.svg",|https://flagcdn.com/w20/pa.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/png.svg",|https://flagcdn.com/w20/pg.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/pry.svg",|https://flagcdn.com/w20/py.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/per.svg",|https://flagcdn.com/w20/pe.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/phl.svg",|https://flagcdn.com/w20/ph.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/pcn.svg",|https://flagcdn.com/w20/pn.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/pol.svg",|https://flagcdn.com/w20/pl.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/prt.svg",|https://flagcdn.com/w20/pt.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/pri.svg",|https://flagcdn.com/w20/pr.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/qat.svg",|https://flagcdn.com/w20/qa.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/mkd.svg",|https://flagcdn.com/w20/mk.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/rou.svg",|https://flagcdn.com/w20/ro.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/rus.svg",|https://flagcdn.com/w20/ru.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/rwa.svg",|https://flagcdn.com/w20/rw.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/reu.svg",|https://flagcdn.com/w20/re.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/blm.svg",|https://flagcdn.com/w20/bl.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/shn.svg",|https://flagcdn.com/w20/sh.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/kna.svg",|https://flagcdn.com/w20/kn.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/lca.svg",|https://flagcdn.com/w20/lc.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/maf.svg",|https://flagcdn.com/w20/mf.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/spm.svg",|https://flagcdn.com/w20/pm.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/vct.svg",|https://flagcdn.com/w20/vc.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/wsm.svg",|https://flagcdn.com/w20/ws.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/smr.svg",|https://flagcdn.com/w20/sm.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/stp.svg",|https://flagcdn.com/w20/st.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/sau.svg",|https://flagcdn.com/w20/sa.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/sen.svg",|https://flagcdn.com/w20/sn.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/srb.svg",|https://flagcdn.com/w20/rs.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/syc.svg",|https://flagcdn.com/w20/sc.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/sle.svg",|https://flagcdn.com/w20/sl.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/sgp.svg",|https://flagcdn.com/w20/sg.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/sxm.svg",|https://flagcdn.com/w20/sx.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/svk.svg",|https://flagcdn.com/w20/sk.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/svn.svg",|https://flagcdn.com/w20/si.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/slb.svg",|https://flagcdn.com/w20/sb.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/som.svg",|https://flagcdn.com/w20/so.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/zaf.svg",|https://flagcdn.com/w20/za.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/sgs.svg",|https://flagcdn.com/w20/gs.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/ssd.svg",|https://flagcdn.com/w20/ss.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/esp.svg",|https://flagcdn.com/w20/es.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/lka.svg",|https://flagcdn.com/w20/lk.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/sdn.svg",|https://flagcdn.com/w20/sd.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/sur.svg",|https://flagcdn.com/w20/sr.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/sjm.svg",|https://flagcdn.com/w20/sj.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/swe.svg",|https://flagcdn.com/w20/se.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/che.svg",|https://flagcdn.com/w20/ch.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/syr.svg",|https://flagcdn.com/w20/sy.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/twn.svg",|https://flagcdn.com/w20/tw.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/tjk.svg",|https://flagcdn.com/w20/tj.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/tza.svg",|https://flagcdn.com/w20/tz.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/tha.svg",|https://flagcdn.com/w20/th.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/tls.svg",|https://flagcdn.com/w20/tl.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/tgo.svg",|https://flagcdn.com/w20/tg.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/tkl.svg",|https://flagcdn.com/w20/tk.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/ton.svg",|https://flagcdn.com/w20/to.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/tto.svg",|https://flagcdn.com/w20/tt.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/tun.svg",|https://flagcdn.com/w20/tn.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/tur.svg",|https://flagcdn.com/w20/tr.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/tkm.svg",|https://flagcdn.com/w20/tm.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/tca.svg",|https://flagcdn.com/w20/tc.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/tuv.svg",|https://flagcdn.com/w20/tv.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/uga.svg",|https://flagcdn.com/w20/ug.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/ukr.svg",|https://flagcdn.com/w20/ua.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/are.svg",|https://flagcdn.com/w20/ae.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/gbr.svg",|https://flagcdn.com/w20/gb.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/umi.svg",|https://flagcdn.com/w20/um.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/usa.svg",|https://flagcdn.com/w20/us.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/ury.svg",|https://flagcdn.com/w20/uy.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/uzb.svg",|https://flagcdn.com/w20/uz.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/vut.svg",|https://flagcdn.com/w20/vu.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/ven.svg",|https://flagcdn.com/w20/ve.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/vnm.svg",|https://flagcdn.com/w20/vn.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/vgb.svg",|https://flagcdn.com/w20/vg.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/vir.svg",|https://flagcdn.com/w20/vi.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/wlf.svg",|https://flagcdn.com/w20/wf.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/esh.svg",|https://flagcdn.com/w20/eh.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/yem.svg",|https://flagcdn.com/w20/ye.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/zmb.svg",|https://flagcdn.com/w20/zm.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/zwe.svg",|https://flagcdn.com/w20/zw.png",|g' top5countries.js logic.js top10countries.js
sed -i 's|https://restcountries.eu/data/ala.svg",|https://flagcdn.com/w20/ax.png",|g' top5countries.js logic.js top10countries.js
